import 'package:get/get.dart';

import '../../routes/app_pages.dart';

class SummaryController extends GetxController {
  final keyPoints = <String>[
    'Discussed Q1 project roadmap',
    'Agreed on new feature priorities',
    'Budget allocation needs review',
    'Team expansion planned for March',
  ];

  final actionItems = <String>[
    'John to prepare budget proposal',
    'Sarah to interview candidates',
    'Mike to update project timeline',
    'Team to review technical specs',
  ];

  final transcript = '''This is a placeholder for the meeting transcript.
  
In a real application, this would contain the full transcription of the recorded meeting, generated by a speech-to-text service.

The transcript would include timestamps and speaker identification for better context and navigation.''';

  void shareSummary() {
    // TODO: Implement share functionality
    Get.snackbar(
      'Share',
      'Share functionality will be implemented',
      snackPosition: SnackPosition.BOTTOM,
    );
  }

  void saveSummary() {
    // TODO: Implement save functionality
    Get.snackbar(
      'Saved',
      'Summary saved successfully',
      snackPosition: SnackPosition.BOTTOM,
    );
    
    // Navigate back to meetings list
    Get.offAllNamed(Routes.MEETINGS);
  }
}